### ISSUE TITLE
Suggestion: use a data format that enforces order

### ISSUE THREAD

**Issue by bphenriques** [MaxVerevkin/wlr-which-key#12]
The current configuration file relies or YAML objects where the order of the keys is not ordered. This makes sense behind the scenes, however from UI PoV, in my use-case I desire a specific order at which they are set:

![Image](https://github.com/user-attachments/assets/14b83f5a-d6c2-48c4-89cb-583c60344550)

My configuration file is generated using `Nix` and throughout the process the order is not guaranteed given the nature of the data structure. In this case, it seems like it is ordered alphabetically.  The order I desire is different than the one shown above. 

There is a argument to be made where my problem is how I generate the config file, however it seems like the data structure should be different in this case. For example:
```yaml
menu:
  - key: ...
    desc: ...
    action: ...
  - key: ...
    desc: ...
    action: ...
  - key: ...
    desc: ....
    action: ...
```

I think this can be retro-compatible.

**Comment by MaxVerevkin** [comment]
I think you are right, semantically list is more appropriate than map here. A list would also work nicely with #10 since keys cannot be lists, so I imagine this is what you want for #10:

```yaml
menu:
  - key: ["h", "Left"]
    desc: Move left
    action: ...
  - key: ["l", "Right"]
    desc: Move right
    action: ...
```
