### ISSUE TITLE
Submenu triggered but not displaying

### ISSUE THREAD

**Issue by khensunny** [MaxVerevkin/wlr-which-key#21]
## Description

I have a power submenu, as seen below and when I triggered it the view doesn't change to show it but the submenu keys still go through. You can check out this video I made:
* I show that the screenshot submenu works fine and then I back out to the main menu
* Then I press `p` to show the power submenu, which doesn't show
* but you can see I press it if you look at the libinput logs in the terminal window

https://github.com/user-attachments/assets/3d6d848f-1734-444d-96df-00a8c9913032

## Build info
version: b427930 (support key repetition)
build command: `cargo build --release --locked`

## Config

```yaml
# Theming
font: Cascadia Code NF
background: "#1e2030ff"
color: "#c8d3f5ff"
border: "#589ed7ff"
separator: " ➜ "
border_width: 2
corner_r: 8
padding: 15 # Defaults to corner_r
rows_per_column: 5 # No limit by default
column_padding: 25 # Defaults to padding

# Anchor and margin
anchor: center # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor is not center
# margin_right: 0
# margin_bottom: 0
# margin_left: 0
# margin_top: 0

# Permits key bindings that conflict with compositor key bindings.
# Default is `false`.
inhibit_compositor_keyboard_shortcuts: false

menu:
  - key: "t"
    desc: Terminal
    cmd: niri msg action spawn -- alacritty msg create-window
  - key: ";"
    desc: Launcher
    cmd: niri msg action spawn -- fuzzel --launch-prefix="niri msg action spawn --"
  - key: "p"
    desc: power
    submenu:
      - key: "d"
        desc: Display off
        cmd: niri msg action power-off-monitors
      - key: "p"
        desc: Shutdown
        cmd: systemctl poweroff
      - key: "r"
        desc: Reboot
        cmd: systemctl reboot
      - key: "s"
        desc: Sleep
        cmd: systemctl suspend
  - key: "s"
    desc: screenshot
    submenu:
      - key: "u"
        desc: UI
        cmd: niri msg action screenshot
      - key: "s"
        desc: Screen
        cmd: niri msg action screenshot-screen
      - key: "w"
        desc: Window
        cmd: niri msg action screenshot-window
```
