### ISSUE TITLE
Can I bind keys like Enter, Space, etc?

### ISSUE THREAD

**Issue by WhyNotHugo** [MaxVerevkin/wlr-which-key#5]
Can I somehow map <kbd>Return</kbd>?

```yaml
menu:
  Return:
    desc: Terminal
    cmd: foot
```
