### ISSUE TITLE
+ and - are no longer valid keys

### ISSUE THREAD

**Issue by nivit** [MaxVerevkin/wlr-which-key#7]
Hi, the last version 1.0.1 no longer accepts `+` and `-` as valid keys. If they are present in the configuration file, you get the following error:

```
Error: Failed to deserialize configuration

Caused by:
    menu: data did not match any variant of untagged enum Entry at line 24 column 3
```
Example (excerpt from my config.):

```
  "s":
    desc: sway
    submenu:
      "b":
        desc: sets border style for focused window
        submenu:
          "c": { desc: csd (client side decoration), cmd: swaymsg border csd }
          "n": { desc: normal layout, cmd: swaymsg border normal pixel 0}
          "o": { desc: none, cmd: swaymsg border none }
          "p": { desc: pixel (4), cmd: swaymsg border pixel 4 }
          "t": { desc: cycles through the available border styles, cmd: swaymsg border toggle }
      "g":
        desc: sets gaps
        submenu:
          "i":
            desc: inner gaps
            submenu:
              "c": { desc: add or remove (toggle) outer gaps (20px), cmd: swaymsg gaps inner current toggle 20 }
              "t": { desc: add or remove (toggle) inner gaps (20px), cmd: swaymsg gaps inner all toggle 20 }
              "+": { desc: add inner gaps (20px), cmd: swaymsg gaps inner all set 20 }
              "-": { desc: remove inner gaps, cmd: swaymsg gaps inner all set 0 }
          "o":
            desc: outer gaps
            submenu:
              "c": { desc: add or remove (toggle) outer gaps (20px), cmd: swaymsg gaps outer current toggle 20 }
              "t": { desc: add or remove (toggle) outer gaps (20px), cmd: swaymsg gaps outer all toggle 20 }
              "+": { desc: add outer gaps (20px), cmd: swaymsg gaps outer all set 20 }
              "-": { desc: remove outer gaps, cmd: swaymsg gaps outer all set 0 }
 
```

wlr-which-key version: 1.0.1
OS version: FreeBSD-14.1-RELEASE
