### ISSUE TITLE
[Feature] Add `include` directive or something like that

### ISSUE THREAD

**Issue by BlueInGreen68** [MaxVerevkin/wlr-which-key#8]
Hi, thanks for the cool project. Is it possible to add an `include` directive to include styles?

For example, i have a file structure like this:

```bash
.config/wlr-which-key/n
└── config.yaml
.config/wlr-which-key/p
└── config.yaml
.config/wlr-which-key/q
└── config.yaml
.config/wlr-which-key/t
└── config.yaml
.config/wlr-which-key/y
└── config.yaml
```

And in each file, I have a standard header:

```yaml
# Theming
font: JetBrainsMono Nerd Font 16
background: "#282828d0"
color: "#fbf1c7"
border: "#8ec07c"
separator: " ➜ "
border_width: 2
corner_r: 10
padding: 15 # Defaults to corner_r

# Anchor and margin
anchor: center # One of center, left, right, top, bottom, bottom-left, top-left, etc.
# Only relevant when anchor is not center
margin_right: 0
margin_bottom: 0
margin_left: 0
margin_top: 0
```
